name: Update Data
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrape new data
        id: scrape
        run: python scrape.py
      - name: Run Model
        if: steps.scrape.outcome == 'success'
        run: |
          sed -i 's/noteParams, _, _/noteParams, helpfulnessScores, _/g' communitynotes/static/sourcecode/main.py
          sed -i 's/process_data.write_scored_notes(noteParams)/process_data.write_scored_notes(noteParams)\n  helpfulnessScores.to_csv("helpfulnessScores.tsv", sep="\\t", index=False)/g' communitynotes/static/sourcecode/main.py
          python communitynotes/static/sourcecode/main.py
        continue-on-error: true  
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data Updated
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
